<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-O0KBCH5" failures="5" tests="8" name="ErrorValidations" time="14.971" errors="0" timestamp="2023-07-06T17:16:31 IST">
  <testcase classname="com.Testcase.DepositValidation" name="TC_01" time="2.8"/>
  <testcase classname="com.Testcase.DepositValidation" name="TC_02" time="2.75"/>
  <testcase classname="com.Testcase.DepositValidation" name="TC_03" time="2.681"/>
  <testcase classname="com.Testcase.DepositValidation" name="TC_04" time="2.322">
    <failure type="java.lang.AssertionError" message="expected [Please fill this field] but found [Please fill out this field.]">
      <![CDATA[java.lang.AssertionError: expected [Please fill this field] but found [Please fill out this field.]
at com.Testcase.DepositValidation.TC_04(DepositValidation.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TC_04 -->
  <testcase classname="com.Testcase.WithdrawlValidation" name="TC01" time="0.002">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.Testcase.WithdrawlValidation.Test(WithdrawlValidation.java:57)
at com.Testcase.WithdrawlValidation.TC01(WithdrawlValidation.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC01 -->
  <testcase classname="com.Testcase.WithdrawlValidation" name="TC02" time="0.003">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.Testcase.WithdrawlValidation.TC02(WithdrawlValidation.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC02 -->
  <testcase classname="com.Testcase.WithdrawlValidation" name="TC03" time="0.002">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.Testcase.WithdrawlValidation.TC03(WithdrawlValidation.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC03 -->
  <testcase classname="com.Testcase.WithdrawlValidation" name="TC04" time="0.002">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.Testcase.WithdrawlValidation.TC04(WithdrawlValidation.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC04 -->
  <testcase classname="com.Base.BaseClass" name="@BeforeTest launchApplication" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest launchApplication -->
</testsuite> <!-- ErrorValidations -->
